name: ci

on:
  push:
    branches: [ legacy, legacy-ci]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare
        uses: ./.github/actions/prepare
      -
        name: Set build tag
        shell: bash
        run: |
          echo "BUILD_TAG=${LAST_COMMIT_SHA:0:7}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/mountaintopsolutions/docker-obs-ndi-ng:legacy-ci-${{BUILD_TAG}}
#             mountaintopsolutions/docker-obs-ndi-ng:legacy-testci-${{BUILD_TAG}}
#          tags: |
#            mountaintopsolutions/docker-obs-ndi-ng:legacy-citest
#            mountaintopsolutions/docker-obs-ndi-ng:1.0-citest
#            ghcr.io/user/app:legacy-latest
#            ghcr.io/mountaintopsolutions/docker-obs-ndi-ng:legacy-1.0
